#!/usr/bin/env node
const moment = require('moment-timezone');
const { timezones, format } = require('./config');
const Table = require('cli-table');

// instantiate
const head = ['Timezone', 'Current Hour'];
const table = new Table({
  head
});

timezones.forEach(tz => table.push([tz, moment.tz(tz).format(format)]));

console.log(table.toString());
